import { NextResponse } from 'next/server'
import { createAdminClient } from '@/lib/supabase'

const SEED_RECIPES = [
  {
    title: 'Dal Tadka',
    description: 'Slow-cooked yellow lentils tempered with cumin, garlic, and red chilies in ghee. A soul-satisfying North Indian classic that tastes like home.',
    time: '35 min', servings: 4, health_score: 88, calories: 280,
    protein: 14, carbs: 42, fat: 7, fiber: 9,
    tags: ['Vegan', 'High Fiber', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'A complete plant-protein meal — lentils supply 14g protein and 9g fiber per serving, keeping you full for hours. Low in fat and rich in folate, iron, and B vitamins. The ghee tempering is a small indulgence that dramatically improves fat-soluble vitamin absorption from the spices.',
    substitutions: ['Replace ghee with cold-pressed coconut oil to make it fully vegan', 'Swap yellow lentils for red lentils (masoor dal) to cut cooking time by 10 minutes'],
    ingredients: [
      '300g (1½ cups) chana dal (split yellow lentils), rinsed and soaked 20 min',
      '1 large brown onion (approx 200g), finely diced',
      '2 medium ripe tomatoes (approx 250g), roughly chopped',
      '6 cloves garlic, 4 minced and 2 thinly sliced',
      '1 x 3cm knob fresh ginger, peeled and finely grated',
      '1½ tsp whole cumin seeds',
      '3 dried Kashmiri red chilies',
      '3 tbsp (45g) ghee, divided',
      '1 tsp ground turmeric',
      '1½ tsp ground coriander',
      '¾ tsp garam masala',
      '1½ tsp fine sea salt, plus more to taste',
      '900ml cold water',
      '1 small bunch fresh coriander, leaves and tender stems roughly chopped',
    ],
    steps: [
      { instruction: 'Drain the soaked lentils and transfer to a medium saucepan. Cover with 900ml cold water, add the turmeric and ½ tsp salt. Bring to a boil, skimming any foam, then reduce heat to a steady simmer.', timer_minutes: 25, pro_tip: 'Skim the foam in the first 3–4 minutes — it removes bitter saponins and gives you a cleaner, sweeter dal.' },
      { instruction: 'While the lentils cook, heat 2 tbsp ghee in a heavy-bottomed kadai or skillet over medium heat. Add the diced onion with a pinch of salt. Cook, stirring every 2–3 minutes, until deeply golden brown.', timer_minutes: 12, pro_tip: 'Patience is everything here. Rushing the onions to pale gold instead of deep amber will flatten the entire flavour profile of the dish.' },
      { instruction: 'Add the minced garlic and grated ginger to the caramelized onions. Stir constantly and cook until the raw smell disappears and the mixture is fragrant and lightly golden.', timer_minutes: 2, pro_tip: 'If the garlic starts to catch on the bottom, add a small splash of water to deglaze and continue cooking.' },
      { instruction: 'Add the chopped tomatoes, ground coriander, and garam masala to the pan. Cook over medium heat, mashing the tomatoes as they soften, until the oil begins to separate visibly at the edges of the masala.', timer_minutes: 8, pro_tip: 'The moment the oil separates (bhuno) is your signal the masala is fully cooked — adding lentils too early results in raw, sour-tasting spices.' },
      { instruction: 'Pour the cooked lentils (with their liquid) into the masala pan. Stir well, taste and adjust salt. Simmer together uncovered to let the flavours meld.', timer_minutes: 5, pro_tip: 'If the dal is too thick, add hot water 50ml at a time. Dal thickens as it cools, so pull it off heat slightly thinner than you want it.' },
      { instruction: 'In a small pan, heat the remaining 1 tbsp ghee over high heat until shimmering. Add the sliced garlic and cumin seeds. Once cumin splutters and the garlic turns golden, immediately add the dried red chilies and stand back. Pour the entire sizzling tadka over the dal and cover immediately to trap the aroma for 60 seconds before stirring.', timer_minutes: 1, pro_tip: 'This final tadka (tempering) is the flavour soul of the dish — do it at the last second and serve immediately for maximum impact.' },
    ],
    tips: 'The key is caramelizing the onions properly — nothing less than 10–12 minutes gives you true depth.',
  },
  {
    title: 'Mediterranean Chickpea Bowl',
    description: 'Crispy roasted chickpeas over herbed quinoa with fresh vegetables and a silky lemon-tahini dressing.',
    time: '30 min', servings: 2, health_score: 94, calories: 420,
    protein: 18, carbs: 58, fat: 12, fiber: 14,
    tags: ['Vegan', 'High Protein', 'Mediterranean', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'One of the most nutritionally complete single-bowl meals you can build — chickpeas and quinoa form a complete amino acid profile together, delivering 18g plant protein. 14g fiber from chickpeas and veg improves satiety and gut microbiome health. The olive oil in the dressing enhances absorption of fat-soluble vitamins from the greens.',
    substitutions: ['Use canned white beans instead of chickpeas for a creamier texture', 'Swap quinoa for bulgur wheat or couscous to reduce cost without losing fiber'],
    ingredients: [
      '1 x 400g can chickpeas, drained, rinsed, and thoroughly patted dry',
      '160g (¾ cup) white quinoa, rinsed well under cold running water',
      '320ml (1⅓ cup) cold water or vegetable stock',
      '200g cherry tomatoes, halved',
      '½ Lebanese cucumber (approx 150g), sliced into half-moons',
      '60g baby spinach leaves',
      '40g kalamata olives, pitted and halved',
      '30g (2 tbsp) hulled tahini',
      '1 large lemon, zested and juiced (approx 50ml juice)',
      '1 small clove garlic, finely grated',
      '2 tbsp extra virgin olive oil, divided',
      '1 tsp ground cumin',
      '½ tsp smoked paprika',
      '½ tsp fine sea salt',
      '2 tbsp fresh flat-leaf parsley, finely chopped',
    ],
    steps: [
      { instruction: 'Preheat oven to 220°C (425°F) fan. Spread the patted-dry chickpeas on a rimmed baking tray. Drizzle with 1 tbsp olive oil, cumin, smoked paprika, and ¼ tsp salt. Toss to coat evenly and spread in a single layer.', timer_minutes: 25, pro_tip: 'The drying step is non-negotiable — any moisture turns the chickpeas steamy in the oven instead of crispy. Pat them for a full 30–40 seconds with paper towels.' },
      { instruction: 'While chickpeas roast, combine rinsed quinoa and water/stock in a small saucepan. Bring to a boil, cover tightly, and reduce to the lowest possible simmer.', timer_minutes: 15, pro_tip: 'Let the quinoa steam off-heat for 5 minutes after cooking, then fluff with a fork — this gives separate, fluffy grains rather than a clumped mass.' },
      { instruction: 'Whisk together tahini, lemon juice, lemon zest, grated garlic, remaining 1 tbsp olive oil, and a pinch of salt. Add cold water 1 tbsp at a time until the dressing is pourable but still creamy.', timer_minutes: 2, pro_tip: 'Tahini seizes up when it first hits acid — keep whisking and adding water drops and it will smooth out into a silky emulsion.' },
      { instruction: 'Divide the warm quinoa between two bowls. Arrange cherry tomatoes, cucumber, spinach, and olives alongside. Top with the roasted chickpeas. Drizzle generously with lemon-tahini dressing and scatter over the chopped parsley.', timer_minutes: 3, pro_tip: 'Assemble just before eating — the heat from the chickpeas and quinoa will very slightly wilt the spinach, which is perfect.' },
    ],
    tips: 'Dry the chickpeas thoroughly before roasting for maximum crunch.',
  },
  {
    title: 'Palak Paneer',
    description: 'Fresh cottage cheese cubes bathed in a velvety, vibrant spinach gravy spiced with cumin and warming garam masala.',
    time: '40 min', servings: 3, health_score: 82, calories: 340,
    protein: 22, carbs: 18, fat: 20, fiber: 6,
    tags: ['Vegetarian', 'High Protein', 'Indian', 'Gluten-Free'],
    image_url: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'An exceptional post-workout meal — paneer delivers all essential amino acids and is one of the highest-protein vegetarian foods at roughly 18g per 100g. Spinach provides iron, magnesium, and vitamin K. The cream and ghee increase caloric density and help absorb fat-soluble vitamins A, D, E, and K from the greens.',
    substitutions: ['Use firm tofu pressed for 15 minutes instead of paneer for a vegan version', 'Swap fresh spinach for frozen spinach (400g, thawed and squeezed dry) to dramatically reduce prep time'],
    ingredients: [
      '400g fresh full-fat paneer, cut into 3cm cubes',
      '500g fresh baby spinach, washed',
      '1 large white onion (approx 220g), roughly chopped',
      '3 medium tomatoes (approx 300g), roughly chopped',
      '5 cloves garlic, roughly chopped',
      '1 x 4cm knob fresh ginger, peeled and roughly chopped',
      '2 green finger chilies, roughly chopped (deseed for mild)',
      '2 tbsp (30g) ghee or neutral oil',
      '1 tsp whole cumin seeds',
      '1 tsp ground cumin',
      '1 tsp ground coriander',
      '½ tsp ground turmeric',
      '¾ tsp garam masala',
      '3 tbsp (45ml) full-fat single cream',
      '1 tsp fine sea salt, plus more to taste',
      '1 tbsp fresh lemon juice',
    ],
    steps: [
      { instruction: 'Bring a large pot of water to a rolling boil. Add the spinach and blanch for exactly 60 seconds until wilted and bright green. Immediately drain and plunge into a bowl of iced water for 2 minutes. Squeeze out all excess water firmly with your hands, then blend to a smooth purée and set aside.', timer_minutes: 5, pro_tip: 'The ice bath is what locks in that vivid restaurant-green colour. Skipping it turns the spinach dull olive-grey within minutes.' },
      { instruction: 'Heat ghee in a heavy kadai over medium-high heat. Lightly pan-fry the paneer cubes in a single layer, turning occasionally, until golden on 2–3 sides. Remove and place on a plate lined with paper towel.', timer_minutes: 5, pro_tip: 'Frying the paneer first seals it so it stays firm and custardy inside during the final simmer instead of crumbling and dissolving into the gravy.' },
      { instruction: 'In the same pan, add cumin seeds. Once they splutter, add the onion and cook over medium heat until translucent and lightly golden. Add garlic, ginger, and green chilies, stirring for 2 minutes. Add tomatoes and all ground spices and cook, mashing the tomatoes, until the oil separates.', timer_minutes: 12, pro_tip: 'This is your masala base — take it to the oil-separation stage (bhuno) before adding any liquid or the final curry will taste raw and flat.' },
      { instruction: 'Allow the onion-tomato masala to cool slightly, then transfer to a blender and blend until smooth. Return to the pan over medium heat, stir in the spinach purée, and simmer together.', timer_minutes: 3, pro_tip: 'Blending the masala (optional but worth it) creates a restaurant-smooth curry base that coats the paneer beautifully.' },
      { instruction: 'Add the pan-fried paneer cubes to the gravy. Stir in the cream and lemon juice. Taste and adjust salt. Simmer gently to heat through — do not boil vigorously or the paneer will toughen.', timer_minutes: 4, pro_tip: 'Add the lemon juice off-heat if you can — the brightness is the final flavour lift that elevates the whole dish.' },
    ],
    tips: 'The ice bath keeps the spinach vivid green — it is the single most important step for colour.',
  },
  {
    title: 'Masala Omelette',
    description: 'Fluffy eggs packed with sautéed onions, fresh green chili, and aromatic spices — the ultimate high-protein Indian breakfast.',
    time: '12 min', servings: 1, health_score: 85, calories: 230,
    protein: 18, carbs: 7, fat: 15, fiber: 2,
    tags: ['High Protein', 'Quick', 'Vegetarian', 'Breakfast'],
    image_url: 'https://images.unsplash.com/photo-1565299507177-b0ac66763828?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'Three whole eggs provide 18–21g of complete protein and a full spectrum of B vitamins, choline, and selenium. At under 250 calories, this is one of the most calorie-efficient high-protein breakfasts possible. The spices (cumin, turmeric) have documented anti-inflammatory properties and add negligible calories.',
    substitutions: ['Use 2 whole eggs + 2 egg whites to cut fat by 5g while keeping protein high', 'Add 30g crumbled paneer or feta inside for an extra 7g protein and calcium boost'],
    ingredients: [
      '3 large free-range eggs',
      '1 small red onion (approx 80g), finely diced',
      '1 medium ripe tomato (approx 100g), seeds removed, finely diced',
      '1 green finger chili, finely chopped (deseed for mild)',
      '1 tbsp (15ml) fresh coriander, finely chopped',
      '¼ tsp ground cumin',
      '¼ tsp ground turmeric',
      '¼ tsp Kashmiri chili powder or mild paprika',
      '¼ tsp fine sea salt',
      '1 tsp (5ml) ghee or neutral oil',
      '1 pinch freshly cracked black pepper',
    ],
    steps: [
      { instruction: 'Crack the eggs into a bowl. Add salt, cumin, turmeric, chili powder, and black pepper. Whisk vigorously for 45 seconds until the mixture is frothy and uniform in colour — no streaks of white should remain.', timer_minutes: 1, pro_tip: 'Vigorous whisking incorporates air for a fluffier omelette. A fork works, but a small balloon whisk is even better.' },
      { instruction: 'Fold in the diced onion, tomato, green chili, and fresh coriander into the egg mixture. Stir to combine evenly.', timer_minutes: 1, pro_tip: 'Patting the diced tomato with paper towel first removes excess moisture that can make the omelette soggy in the centre.' },
      { instruction: 'Heat ghee in a 20–22cm non-stick skillet over medium heat until shimmering. Pour in the egg mixture and immediately reduce heat to medium-low. Do not stir — let the bottom set undisturbed.', timer_minutes: 3, pro_tip: 'Medium-low heat is the secret to a tender omelette. High heat makes eggs rubbery and sets them before you can fold.' },
      { instruction: 'Once the edges look set and the top is 80% cooked but still slightly glossy, fold the omelette in half or thirds with a spatula. Slide immediately onto a warm plate and serve.', timer_minutes: 1, pro_tip: 'Remove from heat 5 seconds before you think it is done — residual heat in the pan will finish the centre perfectly.' },
    ],
    tips: 'Keep heat at medium-low throughout — this is what separates a silky omelette from a rubbery one.',
  },
  {
    title: 'Rajma Chawal',
    description: 'Slow-simmered kidney beans in a rich, dark masala over fluffy basmati rice — the ultimate North Indian comfort meal.',
    time: '55 min', servings: 4, health_score: 90, calories: 380,
    protein: 16, carbs: 68, fat: 5, fiber: 15,
    tags: ['Vegan', 'High Fiber', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Rajma is one of the highest-fiber foods in the Indian pantry at 15g per serving, supporting long-term gut health and stable blood sugar. The beans and rice together form a complete protein, hitting 16g per serving with virtually no fat. Iron and folate content makes this particularly valuable for those following plant-based diets.',
    substitutions: ['Use 2 x 400g cans of kidney beans (drained, rinsed) and skip the overnight soak and pressure cook to cut total time to 30 minutes', 'Swap basmati for brown basmati rice to add 3g extra fiber per serving (increase cooking time by 15 minutes)'],
    ingredients: [
      '300g (1½ cups) dried dark red kidney beans, soaked overnight in cold water (or 2 x 400g cans, drained)',
      '1.5L cold water (for cooking beans)',
      '300g (1½ cups) aged basmati rice, rinsed until water runs clear',
      '2 large onions (approx 350g), finely diced',
      '3 medium tomatoes (approx 300g), blended to a smooth purée',
      '5 cloves garlic, finely grated',
      '1 x 3cm knob fresh ginger, finely grated',
      '2 tbsp neutral oil',
      '1 bay leaf',
      '1 black cardamom pod, lightly crushed',
      '1½ tsp ground cumin',
      '1½ tsp ground coriander',
      '1 tsp garam masala',
      '½ tsp ground turmeric',
      '1 tsp Kashmiri chili powder',
      '1½ tsp fine sea salt',
      '2 tbsp fresh coriander, chopped, to serve',
      'A knob of butter (optional, for serving)',
    ],
    steps: [
      { instruction: 'Drain the soaked kidney beans and transfer to a pressure cooker with 1.5L fresh cold water. Pressure cook for 20–25 minutes (5–6 whistles) until very tender and skins are just beginning to split. Reserve the cooking liquid.', timer_minutes: 25, pro_tip: 'The dark, starchy bean cooking liquid is liquid gold for the gravy — it adds depth and body that plain water cannot replicate. Never discard it.' },
      { instruction: 'Heat oil in a heavy-bottomed pot over medium heat. Add the bay leaf and black cardamom. Once fragrant, add the diced onions with a pinch of salt and cook, stirring regularly, until deep reddish-brown.', timer_minutes: 15, pro_tip: 'Deep brown (not burnt) onions are what gives Punjabi rajma its characteristic dark, glossy colour. This stage cannot be hurried.' },
      { instruction: 'Add garlic and ginger paste. Stir and cook until the raw smell disappears. Pour in the blended tomato purée. Add cumin, coriander, turmeric, and Kashmiri chili. Cook over medium heat until the oil separates visibly at the edges.', timer_minutes: 10, pro_tip: 'Fully cooking the tomato masala until oil separates removes all raw tomato acidity and creates a rounded, sweet base.' },
      { instruction: 'Add the cooked beans and 400ml of their reserved cooking liquid. Stir well. Bring to a gentle boil, then reduce heat and simmer uncovered, mashing 2–3 tablespoons of beans against the pot wall to naturally thicken the gravy.', timer_minutes: 15, pro_tip: "Mashing some beans is the chef's trick for a thick, clingy gravy without any starch or cornflour." },
      { instruction: 'Meanwhile, cook rinsed basmati in fresh salted water using the absorption method (1:1.5 ratio). Once cooked, fluff with a fork. Stir garam masala into the rajma, taste and adjust salt. Finish with a knob of butter (optional). Serve over rice with fresh coriander.', timer_minutes: 12, pro_tip: 'Adding garam masala at the very end preserves its aromatic top notes. Adding it early burns off the volatile compounds you are paying for.' },
    ],
    tips: 'Use the bean cooking liquid as your gravy base — it is the most underrated ingredient in the dish.',
  },
  {
    title: 'Chicken Tikka Masala',
    description: 'Charred, yogurt-marinated chicken simmered in a lusciously creamy, spiced tomato and cashew sauce.',
    time: '60 min', servings: 4, health_score: 74, calories: 480,
    protein: 38, carbs: 22, fat: 26, fiber: 4,
    tags: ['High Protein', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'At 38g protein per serving, this is one of the most protein-dense Indian curries. Boneless thighs have more flavour and resilience to high heat than breast meat, and their fat content keeps the final curry moist even after simmering. The cashew paste replaces heavy cream for a version with better micronutrient density.',
    substitutions: ['Use boneless chicken breast instead of thighs to reduce fat by ~6g per serving, but baste more frequently to prevent drying', 'Replace yogurt with coconut yogurt and cream with coconut cream for a dairy-free version'],
    ingredients: [
      '800g boneless, skinless chicken thighs, cut into 4cm cubes',
      '150g (⅔ cup) full-fat plain Greek yogurt (for marinade)',
      '1½ tbsp fresh lemon juice',
      '1½ tsp Kashmiri chili powder',
      '1 tsp garam masala',
      '1 tsp ground cumin',
      '1 tsp ground turmeric',
      '1½ tsp fine sea salt (for marinade)',
      '2 large white onions (approx 400g), roughly chopped',
      '5 cloves garlic, roughly chopped',
      '1 x 4cm knob fresh ginger, roughly chopped',
      '2 tbsp (30ml) neutral oil',
      '1 x 400g can whole peeled tomatoes, crushed by hand',
      '40g raw cashews, soaked in hot water for 15 minutes and drained',
      '100ml (7 tbsp) full-fat double cream',
      '1 tsp sugar',
      '1 tsp dried fenugreek leaves (kasuri methi)',
      '2 tbsp fresh coriander, chopped',
    ],
    steps: [
      { instruction: 'Combine yogurt, lemon juice, all marinade spices, and salt in a large bowl. Add the chicken cubes and toss until every piece is thoroughly coated. Cover and refrigerate for at least 30 minutes (or overnight for maximum flavour).', timer_minutes: 30, pro_tip: 'Overnight marination allows the lactic acid in yogurt to tenderize the chicken at a cellular level — the difference in texture is remarkable.' },
      { instruction: 'Heat a cast-iron skillet or griddle pan over the highest possible heat until smoking. Cook the marinated chicken in batches (do not crowd the pan), searing for 3–4 minutes per side until charred in spots. Set aside — do not worry about cooking through completely.', timer_minutes: 12, pro_tip: 'The char is non-negotiable. It provides the smoky, tandoor-like complexity that defines this dish. A crowded pan steams instead of sears.' },
      { instruction: 'In a large saucepan, heat oil over medium heat. Cook onions until golden brown. Add garlic and ginger and cook 2 minutes. Add crushed tomatoes. Simmer, stirring occasionally, until the sauce has reduced and thickened.', timer_minutes: 20, pro_tip: 'Reducing the tomato base fully before blending prevents a watery, acidic curry. Look for the oil to pool visibly at the edges.' },
      { instruction: 'Add the soaked and drained cashews to the tomato masala. Let cool for 5 minutes, then transfer to a blender. Blend on high for 90 seconds until completely smooth. Pass through a sieve for an ultra-smooth restaurant-finish sauce (optional).', timer_minutes: 5, pro_tip: 'Cashew paste is the secret to a rich, creamy sauce without relying entirely on cream — it also adds protein and healthy fats.' },
      { instruction: 'Return the blended sauce to the saucepan over medium-low heat. Add the seared chicken pieces with any resting juices. Stir in the cream and sugar. Simmer gently until chicken is completely cooked through. Crush dried fenugreek between your palms and stir in. Adjust salt and serve garnished with fresh coriander.', timer_minutes: 10, pro_tip: 'Rubbing kasuri methi between your palms releases the essential oils, intensifying its distinctive aroma by 3–4x.' },
    ],
    tips: 'The char on the chicken is what separates a great tikka masala from a mediocre one — do not skip the high-heat searing step.',
  },
  {
    title: 'Avocado Toast with Poached Eggs',
    description: 'Silky smashed avocado on toasted sourdough, topped with perfectly poached eggs and a hit of chili flakes and lemon.',
    time: '15 min', servings: 2, health_score: 86, calories: 410,
    protein: 18, carbs: 34, fat: 24, fiber: 8,
    tags: ['Vegetarian', 'Quick', 'Breakfast'],
    image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Avocado provides oleic acid (the heart-healthy fat in olive oil) along with potassium, vitamin E, and 8g fiber. Combined with eggs (complete protein, choline for brain health), this is one of the most nutritionally dense breakfasts per calorie. Sourdough has a lower glycemic index than regular bread due to the fermentation process, supporting stable blood sugar.',
    substitutions: ['Use gluten-free seeded bread to make this coeliac-friendly', 'Top with smoked salmon (50g per serving) instead of eggs for an extra 12g protein and omega-3 fatty acids'],
    ingredients: [
      '2 large, very fresh eggs (the fresher the egg, the better the poach)',
      '2 thick slices sourdough bread (approx 80g each)',
      '1 large ripe Hass avocado (approx 200g flesh)',
      '1 tbsp fresh lemon juice',
      '1 small clove garlic, halved',
      '20ml (1½ tbsp) white wine vinegar (for poaching)',
      '½ tsp dried chili flakes (Aleppo or regular)',
      '1 tbsp extra virgin olive oil',
      '¼ tsp flaky sea salt (such as Maldon)',
      'Freshly cracked black pepper, generously',
      '1 tbsp fresh chives, finely snipped (to garnish)',
    ],
    steps: [
      { instruction: 'Fill a medium saucepan with 8cm of water and add the white wine vinegar. Bring to a gentle simmer (85°C) — you want lazy bubbles, not a rolling boil. Toast the sourdough slices in a toaster or under a grill until deeply golden and crisp.', timer_minutes: 4, pro_tip: 'Vinegar lowers the water\'s pH, which causes egg whites to coagulate faster and wrap tightly around the yolk — the key to a beautifully compact poached egg.' },
      { instruction: 'Halve the avocado, remove the stone, and scoop the flesh into a bowl. Add lemon juice, a pinch of flaky salt, and black pepper. Mash with a fork to your preferred texture — a mix of smooth and chunky is ideal. Taste and adjust seasoning.', timer_minutes: 2, pro_tip: 'Add the lemon juice the moment you cut the avocado — it prevents oxidation (browning) and also brightens the flavour considerably.' },
      { instruction: 'Crack each egg into a separate small ramekin or cup. Create a gentle whirlpool in the simmering water with a spoon. Slide the first egg into the centre of the whirlpool. After 30 seconds, add the second egg. Poach for 3–4 minutes for a runny yolk.', timer_minutes: 4, pro_tip: 'Using very fresh eggs is the single biggest factor in successful poaching — the tight white in fresh eggs holds together, while older eggs spread into ragged wisps.' },
      { instruction: 'Rub each toasted sourdough slice with the cut face of the garlic clove. Divide the mashed avocado between the slices, spreading to the edges. Drain each poached egg on a folded paper towel for 10 seconds, then place on top. Drizzle with olive oil, scatter chili flakes, chives, and a final pinch of flaky salt.', timer_minutes: 2, pro_tip: 'Rubbing toast with raw garlic is a technique borrowed from bruschetta — it adds a gentle, aromatic garlic flavour without any harsh bite or the need to cook additional garlic.' },
    ],
    tips: 'Use the freshest eggs available — this is the single most important factor for clean, compact poached eggs.',
  },
  {
    title: 'Miso Glazed Salmon',
    description: 'Caramelized white miso and mirin-glazed salmon fillets served with sesame-dressed bok choy over jasmine rice.',
    time: '25 min', servings: 2, health_score: 91, calories: 430,
    protein: 44, carbs: 18, fat: 21, fiber: 3,
    tags: ['High Protein', 'Healthy & Light', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'Salmon is among the best dietary sources of omega-3 fatty acids (EPA and DHA), with one serving providing over 2,000mg — the full recommended daily dose. At 44g protein per serving it supports muscle protein synthesis, while the omega-3s actively reduce exercise-induced inflammation. White miso contributes gut-friendly probiotics and umami with minimal calories.',
    substitutions: ['Use skin-on trout fillets as a more affordable alternative with a very similar nutritional profile', 'Swap white miso for red miso (aka) for a stronger, saltier flavour — reduce quantity by 30%'],
    ingredients: [
      '2 x 200g center-cut salmon fillets, skin-on, pin bones removed',
      '3 tbsp (45g) white shiro miso paste',
      '2 tbsp (30ml) mirin',
      '1 tbsp (15ml) sake or dry sherry',
      '1 tsp (5ml) toasted sesame oil',
      '1 tsp (4g) caster sugar',
      '2 heads bok choy, halved lengthways',
      '1 tbsp (15ml) soy sauce (low sodium)',
      '1 tsp sesame seeds, toasted',
      '1 spring onion, thinly sliced on the diagonal',
      '1 tsp fresh ginger, finely grated',
    ],
    steps: [
      { instruction: 'Whisk together miso, mirin, sake, sesame oil, and sugar in a small bowl until completely smooth. Pat the salmon fillets dry with paper towels. Place in a shallow dish and coat all over with the miso glaze. Cover and marinate in the fridge.', timer_minutes: 20, pro_tip: 'Even 20 minutes of marination makes a meaningful difference, but if you can prepare these the night before, the miso begins to cure the fish slightly — the flavour penetrates deeper and the texture becomes firmer and more luxurious.' },
      { instruction: 'Place an oven rack 15cm from the grill element. Preheat the grill (broiler) to maximum. Line a baking tray with foil and place salmon skin-side down. Grill for 7–9 minutes, watching closely in the final 2 minutes.', timer_minutes: 9, pro_tip: 'Do not walk away during the final 2 minutes. The miso sugar goes from perfectly caramelized to burnt in under 60 seconds under high grill heat.' },
      { instruction: 'While salmon grills, heat a non-stick skillet over high heat. Add bok choy cut-side down. Sear without touching for 2 minutes until charred. Flip, add a splash of water, cover, and steam for 1 minute until just tender. Dress with soy sauce and grated ginger.', timer_minutes: 3, pro_tip: 'High-heat charring on the cut face of the bok choy adds a bitter, smoky note that balances the sweet-salty glaze on the salmon beautifully.' },
      { instruction: 'Transfer salmon to plates. Arrange bok choy alongside. Scatter sesame seeds and sliced spring onion over everything. Serve immediately.', timer_minutes: 1, pro_tip: 'The salmon is at its peak the moment it comes out of the grill — the caramelized miso crust starts to lose its lacquer quality as it cools.' },
    ],
    tips: 'Watch the glaze in the final 2 minutes under the grill — the miso sugar burns fast.',
  },
  {
    title: 'Overnight Oats with Berries',
    description: 'Creamy oats soaked in almond milk with chia seeds, layered with mixed berries and a drizzle of almond butter.',
    time: '5 min', servings: 1, health_score: 92, calories: 360,
    protein: 13, carbs: 58, fat: 10, fiber: 12,
    tags: ['Vegan', 'Quick', 'Breakfast'],
    image_url: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Rolled oats contain beta-glucan, a soluble fiber that is one of the most clinically studied foods for lowering LDL cholesterol. The chia seeds add 5g additional fiber and provide plant-based omega-3 ALA. The overnight soak pre-gelatinizes the oat starch, which lowers the glycemic index compared to cooked oats, meaning a slower, more stable energy release.',
    substitutions: ['Use kefir instead of almond milk for a probiotic-rich version with 30% more protein', 'Add 1 tbsp hemp seeds instead of almond butter for omega-3 ALA and a more neutral flavour'],
    ingredients: [
      '80g (¾ cup) old-fashioned rolled oats (not instant)',
      '240ml (1 cup) unsweetened almond milk',
      '1 tbsp (12g) chia seeds',
      '1 tbsp (16g) natural almond butter',
      '1 tsp pure vanilla extract',
      '1 tsp (7g) maple syrup',
      '100g mixed berries (fresh or frozen — blueberries, raspberries, strawberries)',
      '1 pinch fine sea salt',
    ],
    steps: [
      { instruction: 'Add oats, chia seeds, vanilla extract, maple syrup, and a pinch of salt to a 500ml jar or container. Pour over the almond milk and stir thoroughly — the chia seeds need to be fully dispersed to avoid clumping.', timer_minutes: 2, pro_tip: 'Give the jar one more stir 10 minutes into refrigeration — this second stir prevents the chia seeds from settling and clumping at the bottom.' },
      { instruction: 'Seal the jar tightly and refrigerate overnight (minimum 6 hours, up to 3 days). The oats will absorb the milk and swell to a thick, creamy consistency.', timer_minutes: 480, pro_tip: 'Oats prepared 2–3 days ahead actually taste better than ones made the night before — the texture gets creamier and the flavours meld more fully.' },
      { instruction: 'In the morning, remove from the fridge. If the mixture is very thick, loosen with 2–3 tbsp extra almond milk. Top with mixed berries and drizzle with almond butter. Serve cold or at room temperature.', timer_minutes: 2, pro_tip: 'Frozen berries work beautifully here — they thaw overnight in the fridge, releasing their juice which swirls into the oats for natural sweetness and colour.' },
    ],
    tips: 'Prepare a week\'s worth of jars on Sunday — overnight oats keep for 3 days in the fridge.',
  },
  {
    title: 'Butter Chicken',
    description: 'Velvety, mildly spiced tomato and cream curry with tender charred chicken — the dish that captured the world.',
    time: '55 min', servings: 4, health_score: 72, calories: 510,
    protein: 37, carbs: 18, fat: 33, fiber: 3,
    tags: ['High Protein', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'A high caloric density dish with 37g protein per serving making it ideal for muscle-building phases. The chicken provides all essential amino acids, while the cream and butter deliver significant caloric surplus. Despite its indulgent profile, homemade butter chicken has significantly less sodium and preservatives than restaurant or takeaway versions. Consider using chicken breast and reduced cream for a lighter macro profile.',
    substitutions: ['Use paneer (400g) instead of chicken for a vegetarian version with comparable protein content', 'Replace double cream with full-fat coconut cream for a dairy-free version with a subtle, tropical sweetness'],
    ingredients: [
      '800g boneless, skinless chicken thighs, cut into 4cm cubes',
      '150g full-fat plain yogurt',
      '1 tbsp fresh lemon juice',
      '1½ tsp Kashmiri chili powder',
      '1 tsp garam masala (for marinade)',
      '1 tsp ground cumin (for marinade)',
      '1 tsp fine sea salt (for marinade)',
      '2 tbsp (30g) unsalted butter, divided',
      '1 tbsp neutral oil',
      '1 large onion (approx 200g), finely diced',
      '5 cloves garlic, finely grated',
      '1 x 3cm knob fresh ginger, finely grated',
      '1 x 400g can crushed tomatoes',
      '1 tsp ground coriander',
      '½ tsp ground turmeric',
      '1 tsp garam masala (for the sauce)',
      '150ml (⅔ cup) full-fat double cream',
      '1 tsp sugar',
      '1½ tbsp dried fenugreek leaves (kasuri methi)',
      '1 tsp fine sea salt, to taste',
    ],
    steps: [
      { instruction: 'Combine yogurt, lemon juice, and all marinade spices and salt in a large bowl. Add chicken and toss until evenly coated. Cover and marinate in fridge (minimum 30 min, ideally overnight).', timer_minutes: 30, pro_tip: 'Overnight marination noticeably tenderizes the chicken — the lactic acid in yogurt gently breaks down muscle fibres without making them mushy.' },
      { instruction: 'Heat a cast-iron or heavy skillet over the highest possible heat until smoking. Add 1 tbsp oil. Sear the marinated chicken in a single layer without crowding, working in batches. Cook 3–4 minutes per side until charred. Remove and rest.', timer_minutes: 12, pro_tip: 'High-heat charring creates Maillard reaction compounds that are fundamental to the dish\'s smoky, complex flavour. Without this step, it is just a tomato curry.' },
      { instruction: 'In a large heavy saucepan, melt 1 tbsp butter over medium heat. Add onion and cook until golden, about 10 minutes. Add garlic and ginger, cook 2 minutes. Add crushed tomatoes and all remaining spices. Simmer uncovered until sauce thickens considerably and oil separates.', timer_minutes: 18, pro_tip: 'Allow the tomato sauce to reduce until it\'s almost paste-like before adding cream — this concentrates the flavour and prevents a watery final curry.' },
      { instruction: 'Allow the sauce to cool slightly. Transfer to a blender and blend until completely smooth. Pass through a fine-mesh sieve back into the saucepan for a silky smooth restaurant-quality sauce.', timer_minutes: 5, pro_tip: 'Sieving the blended sauce is the professional step that takes the texture from home-cook to restaurant-quality. It removes all skin fragments and fibre for pure velvety smoothness.' },
      { instruction: 'Return blended sauce to medium-low heat. Add seared chicken with all resting juices. Stir in cream, sugar, remaining butter, and salt. Simmer gently for 8–10 minutes. Rub kasuri methi between your palms directly over the pan and stir in. Adjust seasoning and serve.', timer_minutes: 10, pro_tip: 'Adding the butter at the very end (mounting) and stirring to emulsify creates a glossy, coating sauce — the same technique used in classical French pan sauces.' },
    ],
    tips: 'Sieve the blended sauce for a silky, restaurant-quality texture — it takes 60 seconds and makes a transformative difference.',
  },
  {
    title: 'Greek Salad (Horiatiki)',
    description: 'Chunky sun-ripened tomatoes, cucumber, red onion, kalamata olives, and a crown of creamy feta in excellent olive oil.',
    time: '10 min', servings: 2, health_score: 89, calories: 290,
    protein: 10, carbs: 14, fat: 22, fiber: 4,
    tags: ['Vegetarian', 'Quick', 'Mediterranean'],
    image_url: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'A low-carbohydrate, nutrient-dense meal dominated by oleic acid from olive oil and feta — both associated with the Mediterranean diet\'s documented cardiovascular benefits. Feta provides calcium and a surprising 6–8g protein per 60g serving. The combination of fiber from vegetables and healthy fat from olive oil and olives promotes satiety on modest calories.',
    substitutions: ['Use dairy-free feta (cashew-based or store-bought vegan) to make this fully vegan', 'Add a 200g can of drained white beans to increase protein by 8g and turn this into a more substantial main'],
    ingredients: [
      '300g ripe mixed tomatoes (beef, cherry, heirloom — whatever is best quality), cut into large wedges',
      '½ large English cucumber (approx 200g), sliced into thick half-moons',
      '½ red onion (approx 80g), very thinly sliced',
      '80g kalamata olives (bone-in for better flavour)',
      '100g full-fat Greek barrel-aged feta, in a single large block',
      '½ green capsicum (bell pepper), sliced into rings',
      '3 tbsp (45ml) excellent-quality extra virgin olive oil',
      '1 tsp dried Greek oregano (rubbed between palms to release aroma)',
      '¼ tsp flaky sea salt',
      'Freshly cracked black pepper',
      '2 tsp red wine vinegar (optional)',
    ],
    steps: [
      { instruction: 'If using red onion, place the thin slices in a small bowl of ice water for 10 minutes. This removes harsh sulphur compounds, leaving the onion crisp and mild. Drain and pat dry before using.', timer_minutes: 10, pro_tip: 'Soaking raw onion in ice water is a chef\'s technique that makes it 80% more palatable raw — it goes from eye-watering pungent to pleasantly sharp and crisp.' },
      { instruction: 'Arrange the tomato wedges, cucumber, and capsicum rings on a large serving platter. Scatter the red onion and olives over the top. Drizzle generously with olive oil and red wine vinegar if using. Season with flaky salt and pepper.', timer_minutes: 3, pro_tip: 'In authentic horiatiki, the vegetables are arranged rather than tossed — each element retains its identity and the dressing pools naturally at the base.' },
      { instruction: 'Place the entire block of feta on top of the salad. Drizzle the feta directly with a little extra olive oil and finish with a generous pinch of dried oregano rubbed between your palms directly over the salad. Serve immediately with crusty bread.', timer_minutes: 1, pro_tip: 'A single block of feta on top (rather than crumbled) is traditional, and it means each person gets to break off their own chunk — the texture contrast is far superior to pre-crumbled feta.' },
    ],
    tips: 'Never crumble the feta — place it as a whole block and let each person break it themselves at the table.',
  },
  {
    title: 'Paneer Tikka',
    description: 'Smoky, charred paneer cubes with peppers and onion, marinated in spiced yogurt and finished with chaat masala and mint chutney.',
    time: '35 min', servings: 3, health_score: 78, calories: 370,
    protein: 24, carbs: 15, fat: 24, fiber: 3,
    tags: ['Vegetarian', 'High Protein', 'Indian'],
    image_url: 'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'Paneer is an exceptional vegetarian protein source — 100g provides approximately 18–20g complete protein and up to 700mg calcium. The yogurt marinade adds probiotics and helps the spices adhere to the surface. At 370 calories per serving with 24g protein, this is a calorie-efficient, satisfying starter or main that supports muscle protein synthesis.',
    substitutions: ['Use extra-firm tofu (pressed for 20 minutes) instead of paneer for a vegan version — freeze the tofu overnight first for a meatier, more porous texture that absorbs marinade better', 'Add 1 tbsp tandoori masala to the marinade for a deeper, smokier flavour profile with more complexity'],
    ingredients: [
      '400g full-fat paneer, cut into 3–4cm cubes',
      '1 red capsicum (bell pepper), cut into 3cm squares',
      '1 green capsicum (bell pepper), cut into 3cm squares',
      '1 large red onion, cut into 3cm squares, layers separated',
      '150g full-fat plain Greek yogurt',
      '1½ tbsp fresh lemon juice',
      '1½ tsp Kashmiri chili powder',
      '1 tsp garam masala',
      '1 tsp ground cumin',
      '1 tsp ground coriander',
      '½ tsp ground turmeric',
      '1 tsp ginger-garlic paste (or 1 tsp each fresh grated ginger and garlic)',
      '1 tbsp neutral oil',
      '1 tsp fine sea salt',
      '½ tsp chaat masala (to finish)',
      '½ lemon, for squeezing at the table',
      'Mint chutney, to serve',
    ],
    steps: [
      { instruction: 'Combine yogurt, lemon juice, all spices, ginger-garlic paste, oil, and salt in a large bowl. Whisk to a smooth marinade. Add paneer cubes, capsicum squares, and onion. Gently fold to coat everything evenly without breaking the paneer. Marinate for a minimum of 20 minutes at room temperature, or up to 4 hours in the fridge.', timer_minutes: 20, pro_tip: 'Longer marination = deeper colour and flavour penetration. Even 20 minutes makes a visible difference compared to immediate cooking.' },
      { instruction: 'Thread the paneer, capsicum, and onion alternately onto metal skewers (or pre-soaked wooden skewers). Aim for 3–4 pieces of paneer per skewer, interspersed with vegetables.', timer_minutes: 5, pro_tip: 'Alternating paneer and vegetables ensures the veg acts as insulation, preventing the paneer from charring too quickly before the interior heats through.' },
      { instruction: 'Heat a cast-iron griddle pan or skillet over the highest possible heat until smoking. Brush lightly with oil. Cook the skewers without moving for 2–3 minutes until the bottom side develops a deep char. Rotate 90° and char all 4 sides, 2–3 minutes each.', timer_minutes: 12, pro_tip: 'The pan must be truly smoking hot — if it is not, the marinade will weep liquid and the paneer will stew rather than char. Be patient and let the pan heat fully.' },
      { instruction: 'Remove skewers onto a warm plate. Sprinkle immediately with chaat masala and a squeeze of fresh lemon juice. Serve hot with mint chutney and sliced red onion rings.', timer_minutes: 1, pro_tip: 'Chaat masala applied immediately out of the pan creates a tangy, complex crust as it hits the hot, moist surface. Applied cold it just sits on top.' },
    ],
    tips: 'The pan must be smoking hot — a lukewarm pan steams the paneer instead of charring it.',
  },
  {
    title: 'Shakshuka',
    description: 'Eggs poached directly in a smoky, cumin-scented tomato and roasted red pepper sauce — a one-pan Middle Eastern masterpiece.',
    time: '28 min', servings: 2, health_score: 84, calories: 300,
    protein: 17, carbs: 21, fat: 17, fiber: 5,
    tags: ['Vegetarian', 'Mediterranean', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1595295333158-4742f28fbd85?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'A highly nutrient-dense meal with 17g protein from eggs, significant lycopene from cooked tomatoes (cooking increases lycopene bioavailability by 2–3x), and vitamin C from peppers. At 300 calories for a filling, satisfying meal it is one of the best calorie-to-satiety ratios in this collection. The olive oil improves absorption of lycopene, a fat-soluble antioxidant.',
    substitutions: ['Add 80g crumbled feta cheese over the top before poaching for a Greek-inspired version with extra protein and creaminess', 'Stir in 100g canned chickpeas with the tomatoes to make this a more substantial vegan-friendly protein source (skip eggs)'],
    ingredients: [
      '4 large free-range eggs',
      '2 tbsp (30ml) extra virgin olive oil',
      '1 large red onion (approx 180g), finely diced',
      '1 red capsicum (bell pepper, approx 180g), diced',
      '4 cloves garlic, thinly sliced',
      '1 x 400g can crushed tomatoes (best quality)',
      '1 tsp ground cumin',
      '1 tsp sweet smoked paprika',
      '½ tsp ground coriander',
      '¼ tsp cayenne pepper',
      '1 tsp fine sea salt',
      '1 tsp sugar (to balance acidity)',
      '2 tbsp fresh flat-leaf parsley, chopped',
      '2 tbsp fresh coriander, chopped',
      'Crusty bread or pita, to serve',
    ],
    steps: [
      { instruction: 'Heat olive oil in a wide, heavy oven-safe skillet or cast-iron pan (26–28cm) over medium heat. Add onion and capsicum with a pinch of salt. Cook, stirring occasionally, until softened and the onion is translucent.', timer_minutes: 8, pro_tip: 'A wide pan is important — you need a shallow depth of sauce so the egg whites set before the yolks overcook. In a deep saucepan, the eggs will never cook evenly.' },
      { instruction: 'Add the sliced garlic and cook until fragrant, about 60 seconds. Add all the spices — cumin, smoked paprika, coriander, cayenne — and stir into the vegetables for 30 seconds to bloom. Pour in the crushed tomatoes. Add salt and sugar. Stir to combine and bring to a simmer.', timer_minutes: 8, pro_tip: 'Blooming dry spices in the oil before adding liquid releases their fat-soluble aroma compounds into the base — this step takes 30 seconds and dramatically deepens flavour.' },
      { instruction: 'Using the back of a large spoon, create 4 shallow wells in the simmering tomato sauce. Crack one egg carefully into each well, keeping the yolk intact. Season each egg with a tiny pinch of salt and pepper.', timer_minutes: 1, pro_tip: 'Cracking each egg into a small ramekin first gives you control — you can see and remove any shell fragments, and slide it gently without breaking the yolk.' },
      { instruction: 'Cover the pan tightly with a lid or foil and reduce heat to medium-low. Cook until the whites are fully opaque but the yolks are still glossy and runny. Scatter fresh parsley and coriander over the top. Take the pan directly to the table and serve with crusty bread.', timer_minutes: 6, pro_tip: 'Timing is everything here — pull the pan off heat when the whites look 90% set. The residual heat from the sauce will finish the whites perfectly while keeping the yolks soft.' },
    ],
    tips: 'Crack eggs into ramekins first, and cover tightly with a lid for even, steamy cooking.',
  },
  {
    title: 'Aloo Gobi',
    description: 'Potatoes and cauliflower slow-cooked with turmeric and cumin until tender and lightly caramelized, with no added water.',
    time: '38 min', servings: 3, health_score: 87, calories: 220,
    protein: 7, carbs: 38, fat: 7, fiber: 8,
    tags: ['Vegan', 'Indian', 'Healthy & Light'],
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'At just 220 calories per serving, this is one of the leanest satisfying meals in Indian cuisine. Cauliflower is exceptionally high in vitamin C and K and contains sulforaphane, a compound with documented anti-inflammatory properties. Potatoes, despite their reputation, are a very good source of potassium and vitamin B6. The dry-cooking method concentrates flavour without adding calories.',
    substitutions: ['Replace potato with sweet potato for a higher vitamin A and slightly sweeter profile', 'Add 100g frozen green peas in the final 5 minutes for extra protein and a pop of colour'],
    ingredients: [
      '400g waxy potatoes (such as Yukon Gold or Charlotte), peeled and cut into 2.5cm cubes',
      '1 medium cauliflower (approx 600g), broken into small 3cm florets',
      '1 medium white onion (approx 150g), finely diced',
      '3 cloves garlic, finely grated',
      '1 x 2cm knob fresh ginger, finely grated',
      '2 tbsp (30ml) neutral oil',
      '1 tsp whole cumin seeds',
      '½ tsp whole mustard seeds',
      '1 tsp ground turmeric',
      '1½ tsp ground coriander',
      '½ tsp Kashmiri chili powder',
      '¾ tsp fine sea salt',
      '½ tsp garam masala',
      '2 tbsp fresh coriander, chopped',
      '1 tsp fresh lemon juice',
    ],
    steps: [
      { instruction: 'Heat oil in a wide, heavy-bottomed skillet with a lid over medium-high heat. Add cumin and mustard seeds. When they splutter and pop, add the diced onion and cook until lightly golden, stirring occasionally.', timer_minutes: 7, pro_tip: 'Wait until the mustard seeds are truly popping (sounds like light rain) before adding the onion — this fully develops their nutty flavour. If they just sit in the oil, they taste bitter and raw.' },
      { instruction: 'Add garlic and ginger. Stir for 60 seconds until fragrant. Add turmeric, ground coriander, and chili powder. Stir constantly for 30 seconds to bloom the spices in the oil. Add the potato cubes and toss until every piece is coated in the spiced oil.', timer_minutes: 5, pro_tip: 'Coating the potato in turmeric-oil before covering not only colours them beautifully but the oil helps transfer heat evenly to the dense starch.' },
      { instruction: 'Reduce heat to medium-low. Add a pinch of salt, cover tightly with a lid, and cook. Shake the pan every 5 minutes. Resist adding water — the potato and cauliflower release their own steam which cooks everything.', timer_minutes: 15, pro_tip: 'No water is the secret of aloo gobi — adding it makes the veg mushy and watery. The closed lid traps the vegetables\' own moisture and creates a natural steam environment.' },
      { instruction: 'Add the cauliflower florets and toss to coat. Re-cover and cook, shaking the pan every 3–4 minutes, until the cauliflower is just tender and the potatoes are soft with slightly caramelized edges. Remove lid, add garam masala, lemon juice, and fresh coriander. Toss and serve.', timer_minutes: 12, pro_tip: 'Adding cauliflower after the potato has a 10-minute head start ensures both cook to the same doneness simultaneously — cauliflower takes about 12 minutes, potato about 25 total.' },
    ],
    tips: 'Do not add water at any point — the vegetables steam in their own moisture, which keeps the dish perfectly dry and fragrant.',
  },
  {
    title: 'Thai Basil Fried Rice (Khao Pad Krapao)',
    description: 'Wok-tossed jasmine rice with holy basil, bird\'s eye chili, and a crispy fried egg with runny yolk on top.',
    time: '18 min', servings: 2, health_score: 76, calories: 450,
    protein: 16, carbs: 72, fat: 13, fiber: 3,
    tags: ['Quick', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Fried rice is an efficient way to use leftover cooked rice and repurpose it into a complete meal. Day-old rice has a lower glycemic index than freshly cooked rice due to retrogradation of starch. Adding eggs provides complete protein and choline. The high-heat wok technique (wok hei) creates Maillard flavour compounds impossible to replicate on low-heat equipment.',
    substitutions: ['Add 200g minced chicken or pork stir-fried before the rice for a more substantial, higher-protein version', 'Use cauliflower rice instead of jasmine rice for a low-carb version (reduce calories by approximately 200 per serving)'],
    ingredients: [
      '400g (approx 2 cups) day-old cooked jasmine rice, refrigerated overnight',
      '4 large eggs (2 for the rice, 2 for topping)',
      '4 cloves garlic, finely minced',
      '3–5 bird\'s eye chilies, finely minced (adjust to heat tolerance)',
      '1 shallot, finely minced',
      '30g fresh holy basil or Thai basil leaves (stems removed)',
      '2 tbsp (30ml) fish sauce',
      '1 tbsp (15ml) oyster sauce',
      '1 tsp (5ml) soy sauce',
      '1 tsp (4g) caster sugar',
      '3 tbsp (45ml) neutral oil with high smoke point (divided)',
      '4 spring onions, thinly sliced (whites and greens separated)',
      'White pepper, to taste',
      'Lime wedges and cucumber slices, to serve',
    ],
    steps: [
      { instruction: 'Combine fish sauce, oyster sauce, soy sauce, and sugar in a small bowl. Mix until sugar dissolves. This is your stir-fry sauce — have it ready before you heat the wok, as everything moves fast once cooking begins.', timer_minutes: 2, pro_tip: 'Mise en place is absolutely critical for fried rice. Once the wok is hot, you have 6–8 minutes total — there is no time to measure or mix sauces mid-cook.' },
      { instruction: 'Heat a wok or large heavy skillet over the highest heat your burner offers until it begins to smoke. Add 2 tbsp oil. Add garlic, chili, and shallot all at once. Stir-fry for 30–45 seconds — the aromatics should turn golden and fragrant, not burnt.', timer_minutes: 1, pro_tip: 'The wok must be pre-heated until wisps of smoke appear before adding oil. Adding oil to a cold wok results in sticky, greasy fried rice.' },
      { instruction: 'Push aromatics to the side of the wok. Crack 2 eggs into the centre. Scramble quickly with a spatula until just set but still glossy. Add the day-old rice, breaking up any clumps with your spatula. Toss everything together and stir-fry vigorously, letting the rice sit against the hot wok for 20–30 seconds at a time to develop colour.', timer_minutes: 5, pro_tip: 'Letting the rice sit and catch on the hot wok surface creates wok hei — the characteristic breath-of-the-wok smokiness that defines great fried rice.' },
      { instruction: 'Pour the sauce mixture evenly over the rice. Add spring onion whites. Toss to combine and stir-fry for 1 more minute until the sauce is absorbed and rice is evenly coloured. Turn off heat. Add the fresh basil leaves and toss once — the residual heat will wilt the basil perfectly.', timer_minutes: 2, pro_tip: 'Adding basil off-heat is critical. Even 20 seconds of direct high heat turns basil black and bitter. The residual wok heat wilts it gently while keeping it bright green.' },
      { instruction: 'In a separate small frying pan, heat remaining 1 tbsp oil over medium-high heat. Fry the remaining 2 eggs until the whites are crispy and frilly at the edges but the yolk is still runny. Plate the fried rice, top each portion with a crispy fried egg, spring onion greens, and white pepper. Serve with lime wedges and cucumber slices.', timer_minutes: 3, pro_tip: 'The crispy fried egg is not optional — the running yolk mixes into the rice and acts as a natural sauce binder. It is as important to the dish as the basil itself.' },
    ],
    tips: 'Use day-old cold rice — freshly cooked rice is too wet and steams in the wok instead of frying.',
  },
  {
    title: 'Lemon & Herb Spatchcock Roast Chicken',
    description: 'Butterflied and flattened whole chicken with garlic-herb butter under the skin, roasted at high heat for crackling skin and juicy meat.',
    time: '75 min', servings: 4, health_score: 80, calories: 540,
    protein: 50, carbs: 4, fat: 34, fiber: 1,
    tags: ['High Protein', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c7?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'Spatchcocking reduces roasting time by 30% while dramatically improving skin crispiness — the flattened form means all surfaces hit the direct oven heat evenly. At 50g protein per serving, this is one of the highest-protein single-ingredient meals possible. Poultry skin contains oleic acid (the same healthy fat as olive oil) and dramatically improves moisture retention during cooking.',
    substitutions: ['Use bone-in, skin-on chicken pieces (thighs and drumsticks) if spatchcocking feels intimidating — same technique, same result, easier to execute', 'Replace the herb butter with a miso-lemon mixture (2 tbsp white miso + 1 tbsp softened butter + lemon zest) for an umami-rich Japanese-inspired variation'],
    ingredients: [
      '1 x 1.6–1.8kg whole chicken, preferably free-range',
      '80g (5½ tbsp) unsalted butter, at room temperature',
      '4 cloves garlic, finely minced to a paste with ½ tsp salt',
      '1 large lemon, zested (juice reserved)',
      '2 tbsp fresh rosemary leaves, finely chopped',
      '2 tbsp fresh thyme leaves',
      '1 tbsp fresh flat-leaf parsley, finely chopped',
      '1½ tsp fine sea salt (for seasoning)',
      '½ tsp freshly cracked black pepper',
      '1 tbsp (15ml) extra virgin olive oil',
    ],
    steps: [
      { instruction: 'Place chicken breast-side down. Using sharp kitchen scissors, cut firmly along both sides of the backbone and remove it entirely. Flip the chicken breast-side up. Press firmly down on the breastbone with the heel of your hand until you hear a crack and the bird lies flat. Pat the skin completely dry with paper towels. Allow to air-dry uncovered in the fridge for at least 30 minutes (up to overnight).', timer_minutes: 30, pro_tip: 'The air-drying step is the single most important factor for crackling-crisp skin. Moisture is the enemy of crispiness — surface water turns to steam in the oven, which makes skin rubbery.' },
      { instruction: 'Preheat oven to 220°C (425°F) fan. Mix softened butter, garlic paste, lemon zest, rosemary, thyme, and parsley in a bowl. Season with pepper. Gently slide your fingers under the skin of the breasts and thighs, separating it from the meat without tearing. Push the herb butter under the skin and smooth it out evenly with your fingers from the outside. Drizzle skin with olive oil and season all over with salt.', timer_minutes: 10, pro_tip: 'Butter under the skin bastes the meat from the inside as it melts during roasting — this is the key to incredibly moist breast meat, which tends to dry out before the thighs are done.' },
      { instruction: 'Place chicken skin-side up on a roasting rack set inside a roasting tin (or on a heavy cast-iron pan). Roast at 220°C for 45–55 minutes until the skin is deep golden brown and crackling, and the thigh reaches 75°C (165°F) on an instant-read thermometer.', timer_minutes: 50, pro_tip: 'A roasting rack is important — elevating the chicken allows hot air to circulate underneath and crisps the underside of the skin. Without it, the bottom skin steams in the released juices.' },
      { instruction: 'Transfer the chicken to a carving board. Squeeze the reserved lemon juice over the top. Tent loosely with foil and rest. Carve into pieces by cutting through the joints. Pour any collected resting juices over the carved pieces.', timer_minutes: 15, pro_tip: 'The resting period is when the muscle fibres relax and the juices redistribute back through the meat. Cutting immediately loses up to 30% of the juices onto the board.' },
    ],
    tips: 'Rest the chicken for at least 15 minutes before carving — the juices redistribute and you will lose dramatically less when cutting.',
  },
  {
    title: 'Pasta Aglio e Olio',
    description: 'Spaghetti tossed in a silky emulsion of slow-infused garlic oil, fresh parsley, and chili — six ingredients, infinite skill.',
    time: '22 min', servings: 2, health_score: 73, calories: 490,
    protein: 15, carbs: 70, fat: 19, fiber: 4,
    tags: ['Vegan', 'Mediterranean', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Aglio e olio is a masterclass in culinary economy — pasta carbohydrates provide rapid, sustained energy, while the 60ml olive oil per portion delivers a meaningful dose of oleic acid and vitamin E. Garlic contains allicin, which has documented antimicrobial and cardiovascular benefits. The technique of creating an emulsion with pasta water is a foundational Italian cooking skill with wide application.',
    substitutions: ['Add 50g anchovy fillets with the garlic for a deeply savoury, umami-rich version (the anchovies dissolve into the oil and are virtually undetectable as a distinct flavour)', 'Use gluten-free spaghetti to make this coeliac-friendly — the emulsification technique works identically'],
    ingredients: [
      '200g good-quality spaghetti or spaghettoni',
      '80ml (⅓ cup) excellent-quality extra virgin olive oil',
      '6 large cloves garlic, peeled and thinly sliced on a mandoline or knife',
      '1 tsp dried chili flakes (or to taste)',
      '3 tbsp fresh flat-leaf parsley, finely chopped',
      '1 tbsp fine sea salt (for the pasta water)',
      '½ tsp flaky sea salt (for finishing)',
      'Freshly cracked black pepper',
    ],
    steps: [
      { instruction: 'Bring a large pot of water to a rolling boil. Add 1 tbsp fine sea salt — the water should taste pleasantly salty, like a light broth. Add spaghetti and cook for 1 minute less than the package\'s al dente time. Before draining, ladle out 200ml of the cloudy starchy pasta water and reserve.', timer_minutes: 10, pro_tip: 'The pasta water is your secret emulsifying ingredient — it contains dissolved starch that allows the oil and water to form a creamy, coating sauce rather than a greasy pool at the bottom of the bowl.' },
      { instruction: 'While pasta cooks, place sliced garlic and olive oil in a cold skillet. Turn heat to medium-low. Allow the garlic to slowly infuse and turn pale golden, swirling the pan occasionally. This process should take the full pasta cooking time — gentle and slow is the entire technique.', timer_minutes: 10, pro_tip: 'Starting garlic in cold oil is the cardinal rule. Adding garlic to hot oil means the outside burns before the inside softens — you get harsh, acrid garlic instead of sweet, mellow, and fragrant.' },
      { instruction: 'Once garlic is pale golden, add chili flakes and stir for 30 seconds. Drain spaghetti 1 minute early and add directly to the skillet with the garlic oil. Add 80ml of the reserved pasta water. Toss vigorously over medium heat for 90 seconds — the starchy water will emulsify with the oil into a glossy, creamy coating.', timer_minutes: 3, pro_tip: 'Tossing vigorously while adding starchy water creates the emulsion — this is the same technique as making a pan sauce. More water = more emulsification. Start with less and add to adjust.' },
      { instruction: 'Remove pan from heat. Add the fresh parsley, a final drizzle of olive oil, and generously crack black pepper over the top. Toss once more. Taste and adjust salt. Plate immediately into warmed bowls — this dish is at its absolute best the moment it is made.', timer_minutes: 1, pro_tip: 'Adding a small drizzle of fresh, uncooked olive oil off-heat at the end is the finishing technique of many Italian pasta dishes — cooked oil loses its fresh, grassy aroma, which the raw oil adds back.' },
    ],
    tips: 'Start the garlic in cold oil over medium-low heat — this is the entire secret of the dish.',
  },
  {
    title: 'Black Bean Tacos with Chipotle Slaw',
    description: 'Smoky chipotle-seasoned black beans in charred tortillas with lime-dressed crunchy slaw, guacamole, and pickled jalapeños.',
    time: '22 min', servings: 2, health_score: 88, calories: 420,
    protein: 16, carbs: 62, fat: 14, fiber: 15,
    tags: ['Vegan', 'High Fiber', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'Black beans are one of the highest-fiber foods available at roughly 7–8g per 100g cooked, making this dish remarkable for digestive health and long-term satiety. The fiber and resistant starch in beans has been linked to improved insulin sensitivity. Combined with avocado\'s oleic acid and the vitamin C from lime and cabbage, this is a nutritionally exceptional and calorie-efficient meal.',
    substitutions: ['Add 150g cooked bulgur wheat into the beans to stretch the recipe to 3–4 servings and add a complete grain protein', 'Use jackfruit instead of beans for a meaty, pulled-pork texture while keeping the dish plant-based'],
    ingredients: [
      '1 x 400g can black beans, drained and rinsed',
      '6 small (15cm) corn tortillas',
      '1 chipotle chili in adobo sauce, finely minced (plus 1 tsp adobo sauce)',
      '1 tsp ground cumin',
      '½ tsp smoked paprika',
      '½ tsp garlic powder',
      '½ tsp fine sea salt',
      '2 tbsp (30ml) water',
      '200g (about ¼ head) purple cabbage, very finely shredded',
      '1 medium carrot, peeled and grated',
      '2 tbsp fresh lime juice (divided)',
      '1 tbsp extra virgin olive oil',
      '1 pinch caster sugar',
      '1 large ripe Hass avocado',
      '1 clove garlic, finely grated',
      '2 tbsp pickled jalapeños, to serve',
      '4 tbsp fresh coriander leaves, to serve',
    ],
    steps: [
      { instruction: 'Combine shredded cabbage, grated carrot, 1 tbsp lime juice, olive oil, a pinch of sugar, and salt in a bowl. Toss well and set aside to soften and pickle lightly while you prepare the rest of the components. Taste and adjust seasoning.', timer_minutes: 10, pro_tip: 'The short acid-resting time (even 10 minutes) softens the raw cabbage and removes some bitterness while keeping it crunchy — this is a quick-pickle that dramatically improves the texture and palatability.' },
      { instruction: 'Heat a non-stick pan over medium heat. Add drained black beans, chipotle chili, adobo sauce, cumin, smoked paprika, garlic powder, salt, and water. Cook, stirring and mashing some beans against the pan wall until the liquid is absorbed and beans are fragrant and thick.', timer_minutes: 5, pro_tip: 'Mashing 30–40% of the beans against the pan creates a thick, cohesive filling that stays in the taco — if you leave them all whole they roll out with every bite.' },
      { instruction: 'Mash the avocado with the remaining 1 tbsp lime juice, grated garlic, and a pinch of salt. Leave slightly chunky — a rough mash has more texture interest than a smooth paste.', timer_minutes: 2, pro_tip: 'Place the avocado stone into the guacamole and press cling wrap directly onto the surface to prevent oxidation (browning) if making ahead.' },
      { instruction: 'Char the corn tortillas directly over a gas flame for 20–30 seconds per side, or in a dry cast-iron pan over high heat until blistered and pliable with dark spots. Fill each tortilla with smoky beans, a spoonful of guacamole, a mound of slaw, pickled jalapeños, and fresh coriander.', timer_minutes: 5, pro_tip: 'Charring over an open gas flame is not just aesthetic — the slight char adds a smoky, bitter note that balances the rich beans and creamy avocado. Microwaved tortillas are a poor substitute.' },
    ],
    tips: 'Char the tortillas over a gas flame — it transforms them from a vehicle into a key flavour component.',
  },
  {
    title: 'Vegetable Biryani',
    description: 'Fragrant saffron-steeped basmati layered with spiced mixed vegetables and slow-steamed (dum) to aromatic perfection.',
    time: '70 min', servings: 4, health_score: 83, calories: 440,
    protein: 12, carbs: 80, fat: 10, fiber: 10,
    tags: ['Vegan', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1563379091339-03246963d96c?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Biryani is a nutritionally complete meal when made with a variety of vegetables — the diverse phytonutrients from each vegetable type contribute to comprehensive micronutrient coverage. Saffron contains crocin and crocetin, compounds that have documented antioxidant and mood-supporting effects. The dum (sealed steam) cooking method preserves volatile aromatic compounds that would otherwise escape, making the dish disproportionately more fragrant than the ingredients suggest.',
    substitutions: ['Add 400g drained canned chickpeas to the vegetable layer to add 15g protein per serving and transform this into a high-protein vegan main', 'Use a mix of basmati and wild rice (70/30 ratio) for additional fiber and a more complex, nutty flavour'],
    ingredients: [
      '400g (2 cups) aged basmati rice, rinsed until water runs clear',
      '1.2L water with 1½ tsp salt and 2 bay leaves (for parboiling)',
      '10–12 saffron threads, steeped in 3 tbsp warm milk or water',
      '1 medium cauliflower (400g), cut into small florets',
      '2 medium carrots (200g), peeled and cut into 2cm dice',
      '150g green beans, topped and tailed, cut into 3cm lengths',
      '1 large onion (200g), thinly sliced into half-moons',
      '2 medium tomatoes, roughly diced',
      '150g full-fat yogurt',
      '3 tbsp (45ml) neutral oil or ghee (divided)',
      '4 cloves garlic, finely grated',
      '1 x 3cm knob fresh ginger, finely grated',
      '1 tsp whole cumin seeds',
      '2 green cardamom pods, lightly crushed',
      '1 black cardamom pod, lightly crushed',
      '1 bay leaf',
      '1½ tsp biryani masala or garam masala',
      '1 tsp ground coriander',
      '½ tsp ground turmeric',
      '1 tsp Kashmiri chili powder',
      '1 tsp fine sea salt',
      '2 tbsp fresh mint leaves',
      '2 tbsp fresh coriander, chopped',
      '2 tbsp fried onion (birista) — store-bought or home-fried',
    ],
    steps: [
      { instruction: 'Bring 1.2L salted water with bay leaves to a boil. Add rinsed rice and cook for exactly 7–8 minutes — the rice should be about 70% cooked (firm with a visible white core when you bite a grain). Drain immediately through a colander. Spread on a tray to cool slightly and prevent clumping.', timer_minutes: 10, pro_tip: 'Parboiling to 70% is the most critical technical step in biryani. Under-cooked rice will be chalky; over-cooked rice will turn to mush during the final dum. Taste a grain — it should be just barely past crunchy.' },
      { instruction: 'Heat 2 tbsp oil in a wide, heavy-bottomed pot (with a tight-fitting lid) over medium-high heat. Add whole spices (cumin, cardamom pods, bay leaf). Once fragrant, add sliced onions with a pinch of salt and cook until deep golden-brown. Remove half the onions and set aside for topping.', timer_minutes: 12, pro_tip: 'These deeply caramelized onions (birista) are the flavour backbone of biryani. The ones folded into the veg layer add depth; the reserved ones go on top for texture contrast and presentation.' },
      { instruction: 'Add garlic and ginger to the remaining onion in the pot. Cook 2 minutes. Add diced tomatoes and all ground spices. Cook until tomatoes break down and oil separates. Add all vegetables and toss to coat in the masala. Add yogurt and stir until combined. Cover and cook until vegetables are just tender but still have a slight bite.', timer_minutes: 12, pro_tip: 'The vegetables should be slightly underdone at this stage — they will continue to cook during the dum (steam) process. Fully cooked vegetables at this stage become mushy in the final biryani.' },
      { instruction: 'Spread the vegetable masala evenly across the base of the pot. Layer the parboiled rice on top in an even, domed mound. Drizzle the saffron-milk mixture over the rice — don\'t stir. Scatter the reserved fried onions, mint leaves, coriander, and remaining 1 tbsp ghee over the rice.', timer_minutes: 5, pro_tip: 'Drizzling the saffron over just part of the rice (rather than mixing) creates the beautiful orange-and-white streaked effect when served — both visually stunning and flavourfully varied.' },
      { instruction: 'Seal the pot tightly — use a tight-fitting lid, or press a layer of foil over the pot before placing the lid. Cook over medium-high heat for 5 minutes, then reduce to the lowest possible heat and cook undisturbed for 20 minutes. Remove from heat, leave sealed for 5 minutes, then open, gently mix with a wide spatula, and serve.', timer_minutes: 25, pro_tip: 'Never open the lid during dum cooking. The sealed steam cooks the rice, melds the spice layers, and concentrates the aroma. Every time you open the lid you lose irreplaceable fragrant steam.' },
    ],
    tips: 'Never open the lid during the dum (sealed steaming) phase — the trapped steam is the entire cooking mechanism.',
  },
  {
    title: 'French Onion Soup with Gruyère Crouton',
    description: 'Sweet, deeply caramelized onions in a rich sherry-fortified beef broth, crowned with a toasted baguette crouton and a bubbling Gruyère crust.',
    time: '80 min', servings: 4, health_score: 72, calories: 380,
    protein: 13, carbs: 38, fat: 20, fiber: 4,
    tags: ['Vegetarian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'The long caramelization process transforms onion\'s sharp, sulphurous compounds (thiosulfinates) into sweet, complex flavour molecules — a fundamental lesson in the chemistry of cooking. Gruyère is exceptionally high in calcium (950mg per 100g) and provides complete protein. The slow cooking is time-intensive but largely hands-off, making this a practical choice for batch cooking on weekends.',
    substitutions: ['Use vegetable stock with 2 tsp Marmite or soy sauce instead of beef stock to make this fully vegetarian without losing depth', 'Swap Gruyère for Comté or Emmental for a slightly different flavour — both melt equally well'],
    ingredients: [
      '1.2kg (about 6 large) yellow sweet onions, peeled, halved, and very thinly sliced',
      '60g (4 tbsp) unsalted butter',
      '1 tbsp (15ml) extra virgin olive oil',
      '1 tsp fine sea salt',
      '1 tsp caster sugar',
      '2 tbsp (30ml) dry sherry or dry vermouth',
      '100ml (7 tbsp) dry white wine',
      '1.2L rich beef stock (or good-quality vegetable stock)',
      '1 bay leaf',
      '3 sprigs fresh thyme',
      '½ tsp freshly cracked black pepper',
      '8 thin slices baguette, sliced on the diagonal',
      '160g (1½ cups) Gruyère cheese, freshly grated',
      '1 tsp Dijon mustard (optional, for spreading on croutons)',
    ],
    steps: [
      { instruction: 'Melt butter with olive oil in a large, wide, heavy-bottomed pot (a Dutch oven is ideal) over medium heat. Add all the sliced onions and salt. Stir to coat. Reduce heat to medium-low. Cook, stirring every 5–7 minutes, for a full 45–50 minutes until the onions are deeply caramelized — dark mahogany-brown throughout, dramatically reduced in volume, and incredibly fragrant.', timer_minutes: 50, pro_tip: 'This is not a step where you can speed up by increasing heat. Medium-low heat is mandatory. High heat caramelizes the surface and burns the bottom while the centre remains raw and sharp — you need even, slow heat throughout. Use a wide pot and stir the bottom and corners specifically.' },
      { instruction: 'Add sugar in the final 5 minutes of caramelizing if the onions still look pale — it accelerates the Maillard reaction. Add sherry, scraping up all the dark fond (caramelized bits stuck to the bottom) with a wooden spoon. Cook until the alcohol evaporates, then add white wine and reduce by half.', timer_minutes: 5, pro_tip: 'The dark fond on the bottom of the pot is concentrated, caramelized flavour — the deglazing liquid lifts it all back into the soup. This is where a significant portion of the soup\'s depth comes from.' },
      { instruction: 'Add the stock, bay leaf, thyme sprigs, and black pepper. Bring to a gentle simmer. Cook uncovered for 20 minutes to let the flavours meld and the soup reduce slightly. Taste and adjust seasoning — it should be rich, sweet, and deeply savoury.', timer_minutes: 20, pro_tip: 'If the soup tastes one-dimensional after simmering, add 1 tsp soy sauce or a small piece of Parmesan rind — both are natural glutamate boosters that add umami depth without being detectable.' },
      { instruction: 'Toast the baguette slices under the grill until golden on both sides. Spread with Dijon mustard if using. Preheat the grill (broiler) to high. Ladle the soup into 4 oven-safe bowls placed on a baking sheet. Float 2 croutons on top of each bowl. Pile Gruyère generously over the croutons. Slide under the grill for 3–4 minutes until the cheese is melted, bubbling, and blistered. Serve immediately.', timer_minutes: 8, pro_tip: 'Overfilling the bowls is intentional — the crouton should sit proud above the bowl rim, and the cheese should drape down the sides of the bowl and caramelize against the ceramic. This is the signature presentation.' },
    ],
    tips: 'The caramelization of the onions takes a full 45–50 minutes at medium-low heat — this stage cannot be rushed.',
  },
  {
    title: 'Banana Oat Pancakes',
    description: 'Naturally sweet, fluffy three-ingredient pancakes made with overripe bananas, eggs, and rolled oats — no flour, no sugar needed.',
    time: '18 min', servings: 2, health_score: 86, calories: 270,
    protein: 14, carbs: 38, fat: 8, fiber: 4,
    tags: ['Vegetarian', 'Quick', 'Breakfast'],
    image_url: 'https://images.unsplash.com/photo-1565299543923-37dd37887442?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'These pancakes are nutritionally remarkable for their calorie-to-protein ratio — 14g protein at just 270 calories with no added sugar or flour. Overripe bananas have elevated levels of simple sugars (fructose and glucose) that provide the sweetness naturally. The oats contribute beta-glucan (cholesterol-reducing fiber) and slow-release complex carbohydrates for sustained energy. A genuinely nutrient-dense breakfast masquerading as a treat.',
    substitutions: ['Add 1 tbsp natural peanut butter into the batter for healthy fats and extra protein (adds approx 100 calories and 4g protein per serving)', 'Use certified gluten-free oats to make this suitable for those with non-coeliac gluten sensitivity'],
    ingredients: [
      '2 large overripe bananas (the riper and more spotted, the sweeter)',
      '4 large free-range eggs',
      '80g (¾ cup) old-fashioned rolled oats',
      '½ tsp ground cinnamon',
      '¼ tsp pure vanilla extract',
      '1 pinch fine sea salt',
      '1 tsp coconut oil or butter (for cooking)',
      'Fresh berries and a drizzle of honey, to serve',
    ],
    steps: [
      { instruction: 'Place oats in a blender and blend for 30–45 seconds until they form a coarse flour (some texture is desirable — not completely smooth). Add bananas, eggs, cinnamon, vanilla extract, and salt. Blend on medium speed until a smooth, pourable batter forms. Allow to rest for 3 minutes — the oat flour will hydrate and the batter will thicken slightly.', timer_minutes: 5, pro_tip: 'Blending oats to flour first ensures even distribution and prevents the pancakes from having a gritty, uneven texture. Resting the batter for 3 minutes is important — oat flour needs time to absorb liquid.' },
      { instruction: 'Heat a non-stick skillet over medium heat. Add a small amount of coconut oil or butter and wipe to a thin, even layer. The pan is ready when a droplet of water added to the surface evaporates immediately.', timer_minutes: 2, pro_tip: 'Medium heat is critical — these pancakes cook slower than regular pancakes because they have no gluten structure. Too high and the outside burns before the egg in the centre sets.' },
      { instruction: 'Pour approximately 3–4 tbsp batter per pancake into the pan. Cook undisturbed until bubbles form across the entire surface and the edges look matte and set — they will be slightly slower to set than wheat flour pancakes.', timer_minutes: 3, pro_tip: 'Be patient — flipping too early is the #1 banana pancake mistake. The underside must be fully golden before flipping or the pancake will tear. Use a thin spatula and flip decisively.' },
      { instruction: 'Flip and cook the second side for 1–2 minutes until golden. Stack and keep warm while you cook the remaining batter. Serve immediately with fresh berries and a light drizzle of honey.', timer_minutes: 8, pro_tip: 'These pancakes are best eaten immediately — they lose their fluffiness as they cool and the oat structure compresses. If serving in batches, keep finished pancakes in a 90°C oven on a wire rack.' },
    ],
    tips: 'Use deeply spotted, overripe bananas — the more ripe the banana, the sweeter and more banana-forward the pancakes.',
  },
  {
    title: 'Chole Bhature',
    description: 'Deeply spiced, dark chickpeas (chole) served with pillowy deep-fried bread (bhature) — the king of Punjabi street food.',
    time: '65 min', servings: 4, health_score: 69, calories: 570,
    protein: 19, carbs: 84, fat: 18, fiber: 13,
    tags: ['Vegan', 'Indian', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&q=80&w=1080',
    goal: 'Bulking',
    chef_insight: 'Chole bhature is calorie-dense and ideal for bulking phases — chickpeas provide 13g fiber and 19g plant protein per serving, while the deep-fried bhature contributes a significant caloric surplus. Chickpeas are an excellent source of manganese, folate, and iron. The tea bag cooking technique (adding a black tea bag to the boiling chickpeas) is a traditional trick that gives the chole their characteristic deep mahogany colour without altering flavour.',
    substitutions: ['Serve with tandoori roti or whole wheat chapati instead of bhature to reduce calories by approximately 200 per serving while keeping the chole', 'Use canned chickpeas (2 x 400g, drained) to skip the overnight soak and pressure cook — reduce total time to 35 minutes'],
    ingredients: [
      '300g (1½ cups) dried kabuli chickpeas, soaked overnight in cold water',
      '1 black tea bag',
      '1L cold water (for cooking)',
      '2 large onions (approx 350g), finely diced',
      '3 medium tomatoes (approx 300g), blended smooth',
      '5 cloves garlic, finely grated',
      '1 x 3cm knob fresh ginger, finely grated',
      '2 tbsp neutral oil',
      '2 black cardamom pods (badi elaichi)',
      '1 cinnamon stick (5cm)',
      '2 bay leaves',
      '2 tsp chole masala or chana masala powder',
      '1 tsp ground cumin',
      '1 tsp ground coriander',
      '1 tsp amchur (dry mango powder)',
      '½ tsp ground turmeric',
      '1 tsp Kashmiri chili powder',
      '1½ tsp fine sea salt',
      '250g (2 cups) plain flour (maida), for bhature',
      '80g (⅓ cup) full-fat yogurt, for bhature',
      '½ tsp fine sea salt, for bhature',
      '½ tsp sugar, for bhature',
      '½ tsp baking powder, for bhature',
      'Neutral oil, for deep frying',
    ],
    steps: [
      { instruction: 'Drain the soaked chickpeas. Transfer to a pressure cooker with 1L fresh water and the black tea bag. Pressure cook for 20–25 minutes (6 whistles) until very tender. Remove the tea bag. Reserve 250ml cooking liquid.', timer_minutes: 25, pro_tip: 'The tea bag is the authentic technique for achieving authentic dark chole colour. You can also add 1 tsp dried amla (Indian gooseberry) powder for the same effect and extra vitamin C.' },
      { instruction: 'Heat oil in a heavy pot over medium heat. Add whole spices (cardamom, cinnamon, bay leaves). Once fragrant, add onions with a pinch of salt. Cook until very dark golden brown — a full 12–15 minutes. Add garlic and ginger, cook 2 minutes. Add blended tomato purée and all ground spices. Cook until oil separates.', timer_minutes: 20, pro_tip: 'The deeper you caramelize the onions, the darker and richer the chole gravy. Don\'t be afraid of deep brown — near-burnt onions are what give authentic Punjabi chole their characteristic dark, complex flavour.' },
      { instruction: 'While the chole simmers, combine flour, yogurt, salt, sugar, and baking powder in a bowl. Mix to a shaggy dough, then knead for 8–10 minutes until smooth and elastic. Divide into 8 balls. Cover with a damp cloth and rest for 15 minutes.', timer_minutes: 20, pro_tip: 'The yogurt in the bhature dough is essential — it provides acidity that slightly tenderizes the gluten, producing a layered, flaky interior even after deep frying.' },
      { instruction: 'Add cooked chickpeas and 200ml reserved cooking liquid to the masala. Stir, mashing some chickpeas for a thick gravy. Simmer for 10 minutes. Add amchur and adjust salt. Heat oil in a kadai or deep pot to 180°C (350°F). Roll each dough ball into an oval. Slide into the oil and press with a slotted spoon — the bhature will puff. Fry 1–2 minutes per side until puffed and golden. Serve chole and bhature immediately with sliced red onion and pickle.', timer_minutes: 15, pro_tip: 'Bhature must be served the moment they come out of the oil — they deflate within 5 minutes. Press the first side firmly with a slotted spoon immediately on contact with the oil to encourage uniform puffing.' },
    ],
    tips: 'Cook the dried chickpeas with a black tea bag for the authentic deep, dark colour.',
  },
  {
    title: 'Saag Aloo',
    description: 'Earthy spinach and tender baby potatoes in a mustard seed and cumin-tempered masala — a vibrant vegan Indian side or light main.',
    time: '32 min', servings: 3, health_score: 88, calories: 215,
    protein: 8, carbs: 32, fat: 7, fiber: 9,
    tags: ['Vegan', 'Indian', 'High Fiber'],
    image_url: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&q=80&w=1080',
    goal: 'Cutting',
    chef_insight: 'Saag aloo is one of the leanest satisfying Indian dishes — 215 calories with 9g fiber and 8g plant protein. Spinach is nutritionally exceptional: it provides iron (better absorbed when eaten with the vitamin C from lemon), vitamin K (one serving covers the full daily requirement), and folate. The mustard seed tempering releases glucosinolates into the oil, compounds with documented cancer-preventive properties.',
    substitutions: ['Use sweet potato instead of regular potato for a higher beta-carotene (vitamin A precursor) content with a sweeter flavour profile', 'Replace spinach with kale or Swiss chard for a more robust, slightly bitter green that holds its texture better when cooked'],
    ingredients: [
      '500g baby new potatoes (or waxy potatoes), halved',
      '400g fresh spinach, washed (or 300g frozen, thawed and squeezed dry)',
      '1 medium white onion (approx 150g), finely diced',
      '4 cloves garlic, finely grated',
      '1 x 2cm knob fresh ginger, finely grated',
      '1 green finger chili, finely chopped',
      '2 tbsp neutral oil',
      '1 tsp whole mustard seeds',
      '1 tsp whole cumin seeds',
      '1 tsp ground turmeric',
      '1 tsp ground coriander',
      '½ tsp garam masala',
      '¾ tsp fine sea salt',
      '1 tsp fresh lemon juice',
      '2 tbsp fresh coriander, chopped',
    ],
    steps: [
      { instruction: 'Place the halved potatoes in a saucepan, cover with cold salted water, and bring to a boil. Cook until just tender when pierced with the tip of a knife — they should offer slight resistance. Drain and set aside.', timer_minutes: 12, pro_tip: 'Starting potatoes in cold (not boiling) water allows the heat to penetrate gradually and evenly, preventing the outside from becoming mushy before the interior is cooked through.' },
      { instruction: 'While potatoes cook, blanch fresh spinach in boiling water for 60 seconds, then drain and plunge into iced water. Squeeze out every drop of water with your hands, then roughly chop. (If using frozen, simply thaw, squeeze dry, and roughly chop.)', timer_minutes: 5, pro_tip: 'Squeezing out maximum water from the spinach is critical — any retained moisture will turn the dry-cooked aloo into a watery stew and prevent the masala from coating the potato properly.' },
      { instruction: 'Heat oil in a wide, heavy pan over medium-high heat. Add mustard seeds. When they pop and splutter, immediately add cumin seeds. After 20 seconds, add diced onion with a pinch of salt. Cook, stirring regularly, until lightly golden.', timer_minutes: 8, pro_tip: 'The mustard seeds need to be hot enough to pop — if they just sizzle gently without popping, the oil is not hot enough and the seeds will taste raw and bitter instead of nutty.' },
      { instruction: 'Add garlic, ginger, and green chili. Stir for 60 seconds. Add turmeric and ground coriander, stir 30 seconds. Add the parboiled potatoes and toss to coat in the spiced oil. Cook for 3–4 minutes, letting the potatoes colour slightly. Add the chopped blanched spinach and toss everything together until fully combined and heated through. Add garam masala, lemon juice, and fresh coriander. Taste and adjust salt.', timer_minutes: 7, pro_tip: 'Letting the potato sit against the hot pan without stirring for 30-second intervals creates crispy caramelized patches that add texture contrast to the soft spinach.' },
    ],
    tips: 'Squeeze every drop of water from the spinach before adding — retained moisture creates a soggy dish instead of a dry, fragrant masala.',
  },
  {
    title: 'Egg Fried Rice',
    description: 'Wok-charred jasmine rice with silky scrambled eggs, soy-sesame seasoning, and spring onions — a perfect 15-minute leftover transformation.',
    time: '15 min', servings: 2, health_score: 77, calories: 400,
    protein: 15, carbs: 63, fat: 11, fiber: 3,
    tags: ['Vegetarian', 'Quick', 'Comfort Food'],
    image_url: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Day-old refrigerated rice has a lower glycemic index than freshly cooked rice due to starch retrogradation — the starch crystals reform into resistant starch during cooling, which feeds beneficial gut bacteria. Eggs provide all essential amino acids and choline, which is critical for liver function and cognitive health. This is one of the most efficient ways to create a complete, satisfying meal from leftovers.',
    substitutions: ['Add 150g frozen edamame (shelled) in the final minute of cooking to add 12g plant protein and make this a more substantial vegan-friendly meal (omit eggs)', 'Use cauliflower rice instead of jasmine rice for a low-carb version at approximately 200 fewer calories per serving'],
    ingredients: [
      '400g (approx 2 packed cups) cold, day-old cooked jasmine rice',
      '3 large free-range eggs, beaten',
      '3 spring onions, white and green parts separated, thinly sliced',
      '3 cloves garlic, finely minced',
      '2 tbsp (30ml) soy sauce (low sodium)',
      '1 tsp (5ml) toasted sesame oil',
      '½ tsp oyster sauce (optional)',
      '2 tbsp (30ml) neutral oil with high smoke point',
      'White pepper, generous pinch',
      '1 tsp sesame seeds, toasted (to garnish)',
    ],
    steps: [
      { instruction: 'Mix soy sauce, sesame oil, oyster sauce (if using), and white pepper in a small bowl. Set aside within reach. Break up any large clumps of cold rice with your hands before cooking — cold rice clumps together and even clumps in the wok cook unevenly.', timer_minutes: 2, pro_tip: 'Cold, dry, loose rice is the single most important ingredient requirement. Warm or freshly cooked rice releases steam in the wok and produces mushy, gummy fried rice instead of separate, toasted grains.' },
      { instruction: 'Heat a wok or large heavy skillet over maximum heat until it begins to smoke. Add 1 tbsp oil, tilt to coat. Add spring onion whites and garlic. Stir-fry for 30 seconds — they should sizzle and catch colour immediately.', timer_minutes: 1, pro_tip: 'A smoking-hot wok is non-negotiable. If smoke isn\'t coming off the pan before you add oil, you will never achieve wok hei (the smoky, charred flavour of great fried rice).' },
      { instruction: 'Push aromatics to the side. Add remaining 1 tbsp oil to the centre. Pour in beaten eggs. Let sit 10 seconds, then scramble rapidly into large, barely-set curds. Before fully cooked, add all the cold rice on top. Press down and toss vigorously — let the rice sit on the hot wok surface for 15–20 seconds between stirs to develop colour and crispiness.', timer_minutes: 4, pro_tip: 'Adding rice directly on top of the barely-set egg means the egg coats every grain of rice as you toss — this is the technique behind the rich, egg-forward flavour in great fried rice.' },
      { instruction: 'Pour the soy sauce mixture around the edges of the wok (not directly onto the rice) — the sauce hits the hot wok surface first and caramelizes slightly before mixing in. Add spring onion greens and toss once more to combine. Plate immediately and garnish with sesame seeds.', timer_minutes: 2, pro_tip: 'Pouring sauce around the wok edge instead of directly onto the food is a classical Chinese cooking technique — the sauce hits the hottest part of the wok first, where it caramelizes and creates deeper, more complex flavour before mixing with the rice.' },
    ],
    tips: 'The wok must be smoking before you add oil — this is the foundation of wok hei.',
  },
  {
    title: 'Mango Lassi',
    description: 'Creamy, saffron-kissed yogurt and mango drink with cardamom — the definitive Indian summer cooler.',
    time: '5 min', servings: 2, health_score: 82, calories: 230,
    protein: 8, carbs: 44, fat: 3, fiber: 2,
    tags: ['Vegetarian', 'Indian', 'Quick'],
    image_url: 'https://images.unsplash.com/photo-1623065422902-30a2d299bbe4?auto=format&fit=crop&q=80&w=1080',
    goal: 'Balanced',
    chef_insight: 'Mango is one of the richest sources of vitamin C (one Alphonso mango covers 76% of daily requirements) and beta-carotene (provitamin A). Full-fat yogurt provides probiotics for gut health and bioavailable calcium. As a post-workout recovery drink, the combination of simple sugars (fast glucose replenishment), protein from yogurt, and electrolytes from mango makes this nutritionally superior to most sports drinks.',
    substitutions: ['Use coconut yogurt instead of dairy yogurt for a vegan version with a complementary tropical flavour profile', 'Add ½ tsp turmeric and a crack of black pepper for a golden anti-inflammatory upgrade (the pepper dramatically increases curcumin absorption)'],
    ingredients: [
      '2 large ripe Alphonso mangoes (approx 400g fresh flesh) or 300g high-quality canned mango pulp',
      '300g (1¼ cups) full-fat plain yogurt, cold',
      '100ml (7 tbsp) whole cold milk',
      '4 green cardamom pods, seeds removed and ground to a fine powder',
      '8–10 saffron threads, briefly dry-toasted and crushed',
      '1 tsp pure honey or sugar (optional — depends on mango sweetness)',
      'Crushed ice, to serve',
    ],
    steps: [
      { instruction: 'If using fresh mangoes, peel, cut away the flesh from the stone, and roughly chop. For canned mango pulp, measure directly. Dry-toast saffron threads in a small pan for 20 seconds over medium heat until fragrant and slightly darkened, then crush between your fingers over the blender jug.', timer_minutes: 3, pro_tip: 'Briefly dry-toasting the saffron threads before crushing them releases up to 3x more colour and aroma compounds than adding them raw. This takes 20 seconds and is worth every one of them.' },
      { instruction: 'Add mango, cold yogurt, cold milk, ground cardamom, crushed saffron, and honey/sugar (if using) to a blender. Blend on high for 60 seconds until completely smooth, thick, and creamy. Taste — adjust sweetness if needed. If too thick, add a splash more milk.', timer_minutes: 2, pro_tip: 'Cold yogurt and milk are important — blending warm dairy creates a thin, foamy drink rather than the thick, velvety consistency that defines a great lassi.' },
    ],
    tips: 'Alphonso mangoes (Hapus) have a uniquely rich, honey-like flavour that no other variety matches — seek them out when in season.',
  },
]

export async function GET() {
  try {
    const admin = createAdminClient()

    // --- NUCLEAR RESET STEP ---
    // This deletes everything in the table first!
    await admin.from('recipes').delete().neq('id', '00000000-0000-0000-0000-000000000000')

    const results: string[] = []
    for (let i = 0; i < SEED_RECIPES.length; i += 5) {
      // Stripping out 'tips' before inserting to match your DB schema
      const batch = SEED_RECIPES.slice(i, i + 5).map(({ tips, ...dbReadyRecipe }) => dbReadyRecipe)

      const { data, error } = await admin
        .from('recipes')
        .insert(batch as any)
        .select('id, title')

      if (error) {
        console.error('[seed] Insert error:', error.message)
        continue
      }

      data?.forEach((r: any) => results.push(r.title))
    }

    return NextResponse.json({
      message: `Database Purged and Re-Seeded with ${results.length} high-quality recipes.`,
      titles: results,
    })

  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err)
    return NextResponse.json({ error: `Seed failed: ${message}` }, { status: 500 })
  }
}
